### ISSUE TITLE
Vagrant up command not working properly

### ISSUE THREAD

**Issue by gaurav7019** [WikipediaLibrary/twlight_vagrant#9]
My environment was all ready but suddenly the local site stopped working and said "2003, "Can't connect to MySQL server on '127.0.0.1' (107)". Upon doing mysql -u"twlight" -p"vagrant" in vagrant, "Command 'mysql' not found" shows up! I destroyed the environment and did vagrant up again. Below are the logs. Please help me out.
/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/util/which.rb:37: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
Bringing machine 'twlight' up with 'virtualbox' provider...
==> twlight: Cloning VM...
==> twlight: Matching MAC address for NAT networking...
==> twlight: Checking if box 'bento/debian-8' version '201812.27.0' is up to date...
==> twlight: Setting the name of the VM: twlight_vagrant_twlight_1553421946922_45654
==> twlight: Clearing any previously set network interfaces...
==> twlight: Preparing network interfaces based on configuration...
    twlight: Adapter 1: nat
==> twlight: Forwarding ports...
    twlight: 22 (guest) => 2222 (host) (adapter 1)
==> twlight: Running 'pre-boot' VM customizations...
==> twlight: Booting VM...
==> twlight: Waiting for machine to boot. This may take a few minutes...
    twlight: SSH address: 127.0.0.1:2222
    twlight: SSH username: vagrant
    twlight: SSH auth method: private key
    twlight:
    twlight: Vagrant insecure key detected. Vagrant will automatically replace
    twlight: this with a newly generated keypair for better security.
    twlight:
    twlight: Inserting generated public key within guest...
    twlight: Removing insecure key from the guest if it's present...
    twlight: Key inserted! Disconnecting and reconnecting using new SSH key...
==> twlight: Machine booted and ready!
==> twlight: Checking for guest additions in VM...
    twlight: The guest additions on this VM do not match the installed version of
    twlight: VirtualBox! In most cases this is fine, but in rare cases it can
    twlight: prevent things such as shared folders from working properly. If you see
    twlight: shared folder errors, please make sure the guest additions within the
    twlight: virtual machine match the version of VirtualBox you have installed on
    twlight: your host and reload your VM.
    twlight:
    twlight: Guest Additions Version: 5.2.22
    twlight: VirtualBox Version: 6.0
==> twlight: Setting hostname...
==> twlight: Mounting shared folders...
    twlight: /vagrant => /mnt/c/Users/gaurav/twlight_vagrant
    twlight: /tmp/vagrant-puppet/environments => /mnt/c/Users/gaurav/twlight_vagrant/puppet/environments
    twlight: /tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815 => /mnt/c/Users/gaurav/twlight_vagrant/puppet/modules
==> twlight: Running provisioner: shell...
    twlight: Running: inline script
    twlight: Defaults    env_keep+=SSH_AUTH_SOCK
==> twlight: Running provisioner: shell...
    twlight: Running: inline script
    twlight: Selecting previously unselected package puppetlabs-release-pc1.
    twlight: (Reading database ... 32018 files and directories currently installed.)
    twlight: Preparing to unpack .../puppetlabs-release-pc1-jessie.deb ...
    twlight: Unpacking puppetlabs-release-pc1 (1.1.0-2jessie) ...
    twlight: Setting up puppetlabs-release-pc1 (1.1.0-2jessie) ...
    twlight: WARNING:
    twlight: apt
    twlight:
    twlight: does not have a stable CLI interface yet.
    twlight: Use with caution in scripts.
    twlight: Ign http://apt.puppetlabs.com jessie InRelease
    twlight: Get:1 http://apt.puppetlabs.com jessie Release.gpg [819 B]
    twlight: Get:2 http://apt.puppetlabs.com jessie Release [86.7 kB]
    twlight: Get:3 http://apt.puppetlabs.com jessie/PC1 amd64 Packages [34.5 kB]
    twlight: Ign http://apt.puppetlabs.com jessie/PC1 Translation-en_US
    twlight: Ign http://apt.puppetlabs.com jessie/PC1 Translation-en
    twlight: Err http://security.debian.org jessie/updates InRelease
    twlight:
    twlight: Err http://security.debian.org jessie/updates Release.gpg
    twlight:   Cannot initiate the connection to security.debian.org:80 (2401:2500:103:11a::74). - connect (101: Network is unreachable) [IP: 2401:2500:103:11a::74 80]
    twlight: Err http://httpredir.debian.org jessie InRelease
    twlight:
    twlight: Err http://httpredir.debian.org jessie-updates InRelease
    twlight:
    twlight: Err http://httpredir.debian.org jessie Release.gpg
    twlight:   Cannot initiate the connection to cdn-fastly.deb.debian.org:80 (2a04:4e42:25::204). - connect (101: Network is unreachable) [IP: 2a04:4e42:25::204 80]
    twlight: Err http://httpredir.debian.org jessie-updates Release.gpg
    twlight:   Cannot initiate the connection to cdn-fastly.deb.debian.org:80 (2a04:4e42:25::204). - connect (101: Network is unreachable) [IP: 2a04:4e42:25::204 80]
    twlight: Fetched 122 kB in 4min 4s (499 B/s)
    twlight: Reading package lists...
    twlight: Building dependency tree...
    twlight: Reading state information...
    twlight: 1 package can be upgraded. Run 'apt list --upgradable' to see it.
    twlight: W
    twlight: :
    twlight: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease
    twlight: W
    twlight: :
    twlight: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease
    twlight: W
    twlight: :
    twlight: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease
    twlight: W
    twlight: :
    twlight: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Cannot initiate the connection to security.debian.org:80 (2401:2500:103:11a::74). - connect (101: Network is unreachable) [IP: 2401:2500:103:11a::74 80]
    twlight: W
    twlight: :
    twlight: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Cannot initiate the connection to cdn-fastly.deb.debian.org:80 (2a04:4e42:25::204). - connect (101: Network is unreachable) [IP: 2a04:4e42:25::204 80]    twlight: W
    twlight: :
    twlight: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Cannot initiate the connection to cdn-fastly.deb.debian.org:80 (2a04:4e42:25::204). - connect (101: Network is unreachable) [IP: 2a04:4e42:25::204 80]
    twlight: W
    twlight: :
    twlight: Some index files failed to download. They have been ignored, or old ones used instead.
    twlight:
    twlight: WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.
    twlight: Reading package lists...
    twlight: Building dependency tree...
    twlight:
    twlight: Reading state information...
    twlight: The following extra packages will be installed:
    twlight:   libtomcrypt0 libtommath0 timelimit vim-runtime
    twlight: Suggested packages:
    twlight:   ctags vim-doc vim-scripts
    twlight: The following NEW packages will be installed:
    twlight:   chrony libtomcrypt0 libtommath0 puppet-agent timelimit vim vim-runtime
    twlight: 0 upgraded, 7 newly installed, 0 to remove and 1 not upgraded.
    twlight: Need to get 23.4 MB of archives.
    twlight: After this operation, 123 MB of additional disk space will be used.
    twlight: Get:1 http://apt.puppetlabs.com/ jessie/PC1 puppet-agent amd64 1.10.14-1jessie [16.7 MB]
    twlight: Get:2 http://httpredir.debian.org/debian/ jessie/main libtommath0 amd64 0.42.0-1.1 [52.0 kB]
    twlight: Get:3 http://httpredir.debian.org/debian/ jessie/main libtomcrypt0 amd64 1.17-6 [324 kB]
    twlight: Get:4 http://httpredir.debian.org/debian/ jessie/main timelimit amd64 1.8-1 [14.4 kB]
    twlight: Get:5 http://httpredir.debian.org/debian/ jessie/main vim-runtime all 2:7.4.488-7+deb8u3 [5,048 kB]
    twlight: Get:6 http://httpredir.debian.org/debian/ jessie/main vim amd64 2:7.4.488-7+deb8u3 [953 kB]
    twlight: Get:7 http://httpredir.debian.org/debian/ jessie/main chrony amd64 1.30-2+deb8u2 [253 kB]
    twlight: Get:8 http://apt.puppetlabs.com/ jessie/PC1 puppet-agent amd64 1.10.14-1jessie [16.7 MB]
    twlight: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    twlight: Fetched 21.2 MB in 3min 28s (102 kB/s)
    twlight: Selecting previously unselected package libtommath0.
(Reading database ... 85%abase ...
    twlight: (Reading database ... 90%
    twlight: (Reading database ... 95%
(Reading database ... 32023 files and directories currently installed.)
    twlight: Preparing to unpack .../libtommath0_0.42.0-1.1_amd64.deb ...
    twlight: Unpacking libtommath0 (0.42.0-1.1) ...
    twlight: Selecting previously unselected package libtomcrypt0:amd64.
    twlight: Preparing to unpack .../libtomcrypt0_1.17-6_amd64.deb ...
    twlight: Unpacking libtomcrypt0:amd64 (1.17-6) ...
    twlight: Selecting previously unselected package puppet-agent.
    twlight: Preparing to unpack .../puppet-agent_1.10.14-1jessie_amd64.deb ...
    twlight: Unpacking puppet-agent (1.10.14-1jessie) ...
    twlight: Selecting previously unselected package timelimit.
    twlight: Preparing to unpack .../timelimit_1.8-1_amd64.deb ...
    twlight: Unpacking timelimit (1.8-1) ...
    twlight: Selecting previously unselected package vim-runtime.
    twlight: Preparing to unpack .../vim-runtime_2%3a7.4.488-7+deb8u3_all.deb ...
    twlight: Adding 'diversion of /usr/share/vim/vim74/doc/help.txt to /usr/share/vim/vim74/doc/help.txt.vim-tiny by vim-runtime'
    twlight: Adding 'diversion of /usr/share/vim/vim74/doc/tags to /usr/share/vim/vim74/doc/tags.vim-tiny by vim-runtime'
    twlight: Unpacking vim-runtime (2:7.4.488-7+deb8u3) ...
    twlight: Selecting previously unselected package vim.
    twlight: Preparing to unpack .../vim_2%3a7.4.488-7+deb8u3_amd64.deb ...
    twlight: Unpacking vim (2:7.4.488-7+deb8u3) ...
    twlight: Selecting previously unselected package chrony.
    twlight: Preparing to unpack .../chrony_1.30-2+deb8u2_amd64.deb ...
    twlight: Unpacking chrony (1.30-2+deb8u2) ...
    twlight: Processing triggers for man-db (2.7.0.2-5) ...
    twlight: Processing triggers for systemd (215-17+deb8u8) ...
    twlight: Setting up libtommath0 (0.42.0-1.1) ...
    twlight: Setting up libtomcrypt0:amd64 (1.17-6) ...
    twlight: Setting up puppet-agent (1.10.14-1jessie) ...
    twlight: Created symlink from /etc/systemd/system/multi-user.target.wants/puppet.service to /lib/systemd/system/puppet.service.
    twlight: Created symlink from /etc/systemd/system/multi-user.target.wants/mcollective.service to /lib/systemd/system/mcollective.service.
    twlight: Created symlink from /etc/systemd/system/multi-user.target.wants/pxp-agent.service to /lib/systemd/system/pxp-agent.service.
    twlight: Removed symlink /etc/systemd/system/multi-user.target.wants/pxp-agent.service.
    twlight: Setting up timelimit (1.8-1) ...
    twlight: Setting up vim-runtime (2:7.4.488-7+deb8u3) ...
    twlight: Processing /usr/share/vim/addons/doc
    twlight: Setting up vim (2:7.4.488-7+deb8u3) ...
    twlight: update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
    twlight: update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
    twlight: update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
    twlight: update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
    twlight: update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
    twlight: update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
    twlight: update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
    twlight: Setting up chrony (1.30-2+deb8u2) ...
    twlight:
    twlight: Creating config file /etc/chrony/chrony.conf with new version
    twlight: Processing triggers for libc-bin (2.19-18+deb8u10) ...
    twlight: Processing triggers for systemd (215-17+deb8u8) ...
==> twlight: Running provisioner: shell...
    twlight: Running: inline script
    twlight: # github.com SSH-2.0-babeld-c6e8f0d0
==> twlight: Running provisioner: shell...
    twlight: Running: inline script
    twlight: Notice: Preparing to install into /vagrant/puppet/modules ...
    twlight: Notice: Module jsnshrmn/twlight 0.5.2 is already installed.
==> twlight: Running provisioner: puppet...
==> twlight: Running Puppet with environment local...
==> twlight: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> twlight:                     with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/apt/manifests/source.pp", 23]:
==> twlight:    (at /tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> twlight: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> twlight:                     with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/apt/manifests/source.pp", 24]:
==> twlight:    (at /tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> twlight: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> twlight:                     with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/apt/manifests/source.pp", 25]:
==> twlight:    (at /tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> twlight: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Numeric instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/apt/manifests/source.pp", 126]:
==> twlight:    (at /tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> twlight: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> twlight:                     with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/apt/manifests/setting.pp", 18]:
==> twlight:    (at /tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> twlight: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/apt/manifests/pin.pp", 45]:
==> twlight:    (at /tmp/vagrant-puppet/modules-3c6e31633cd724d7b52193116ab02815/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> twlight: Notice: Compiled catalog for twlight.vagrant.localdomain in environment local in 2.99 seconds
==> twlight: Notice: /Stage[main]/Twlight::Repo/Package[apt-transport-https]/ensure: created
==> twlight: Notice: /Stage[main]/Apt/File[preferences]/ensure: created
==> twlight: Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: defined content as '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
==> twlight: Notice: /Stage[main]/Twlight::Repo/Apt::Source[nodesource]/Apt::Key[Add key: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280 from Apt::Source nodesource]/Apt_key[Add key: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280 from Apt::Source nodesource]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Repo/Apt::Source[mariadb]/Apt::Key[Add key: 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB from Apt::Source mariadb]/Apt_key[Add key: 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB from Apt::Source mariadb]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Repo/Apt::Source[nodesource]/Apt::Pin[nodesource]/Apt::Setting[pref-nodesource]/File[/etc/apt/preferences.d/nodesource.pref]/ensure: defined content as '{md5}744ea20e8a589d988465eee985a7fa73'
==> twlight: Notice: /Stage[main]/Twlight::Repo/Apt::Source[nodesource]/Apt::Setting[list-nodesource]/File[/etc/apt/sources.list.d/nodesource.list]/ensure: defined content as '{md5}1838b828256db9aed447649597decfa7'
==> twlight: Notice: /Stage[main]/Twlight::Repo/Apt::Source[mariadb]/Apt::Pin[mariadb]/Apt::Setting[pref-mariadb]/File[/etc/apt/preferences.d/mariadb.pref]/ensure: defined content as '{md5}adec534b69df19e22f63d9e42e0f9464'
==> twlight: Notice: /Stage[main]/Twlight::Repo/Apt::Source[mariadb]/Apt::Setting[list-mariadb]/File[/etc/apt/sources.list.d/mariadb.list]/ensure: defined content as '{md5}1590432fad94741dcbde6f203133bc14'
==> twlight: Error: /Stage[main]/Apt::Update/Exec[apt_update]: Failed to call refresh: Command exceeded timeout
==> twlight: Error: /Stage[main]/Apt::Update/Exec[apt_update]: Command exceeded timeouts
==> twlight: Notice: /Stage[main]/Twlight::Install/Exec[apt-update]/returns: executed successfully
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[build-essential]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[gettext]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[git]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[libmariadb-client-lgpl-dev]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[mariadb-client]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[mariadb-server]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[nginx]/ensure: created
==> twlight: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install nodejs' returned 100: Reading package lists...
==> twlight: Building dependency tree...
==> twlight: Reading state information...
==> twlight: The following NEW packages will be installed:
==> twlight:   nodejs
==> twlight: 0 upgraded, 1 newly installed, 0 to remove and 45 not upgraded.
==> twlight: Need to get 13.5 MB of archives.
==> twlight: After this operation, 64.3 MB of additional disk space will be used.
==> twlight: Err https://deb.nodesource.com/node_8.x/ jessie/main nodejs amd64 8.15.1-1nodesource1
==> twlight:   Connection timed out after 120001 milliseconds
==> twlight: E: Failed to fetch https://deb.nodesource.com/node_8.x/pool/main/n/nodejs/nodejs_8.15.1-1nodesource1_amd64.deb  Connection timed out after 120001 milliseconds
==> twlight:
==> twlight: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> twlight: Error: /Stage[main]/Twlight::Install/Package[nodejs]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install nodejs' returned 100: Reading package lists...
==> twlight: Building dependency tree...
==> twlight: Reading state information...
==> twlight: The following NEW packages will be installed:
==> twlight:   nodejs
==> twlight: 0 upgraded, 1 newly installed, 0 to remove and 45 not upgraded.
==> twlight: Need to get 13.5 MB of archives.
==> twlight: After this operation, 64.3 MB of additional disk space will be used.
==> twlight: Err https://deb.nodesource.com/node_8.x/ jessie/main nodejs amd64 8.15.1-1nodesource1
==> twlight:   Connection timed out after 120001 milliseconds
==> twlight: E: Failed to fetch https://deb.nodesource.com/node_8.x/pool/main/n/nodejs/nodejs_8.15.1-1nodesource1_amd64.deb  Connection timed out after 120001 milliseconds
==> twlight:
==> twlight: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[pandoc]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[python-dev]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Package[python-pip]/ensure: created
==> twlight: Notice: /Stage[main]/Twlight::Install/Exec[virtualenv_install]/returns: executed successfully
==> twlight: Notice: /Stage[main]/Twlight::Configsys/User[www]: Dependency Package[nodejs] has failures: true
==> twlight:
==> twlight: Notice: /Stage[main]/Twlight::Configsys/File[/var/lib/mysql/ibdata1]: Dependency Package[nodejs] has failures: true
==> twlight: Warning: /Stage[main]/Twlight::Configsys/User[www]: Skipping because of failed dependencies
==> twlight: Warning: /Stage[main]/Twlight::Configsys/File[/var/lib/mysql/ibdata1]: Skipping because of failed dependencies
==> twlight: Notice: /Stage[main]/Twlight::Configsys/File[/var/lib/mysql/ib_logfile0]: Dependency Package[nodejs] has failures: true
==> twlight: Warning: /Stage[main]/Twlight::Configsys/File[/var/lib/mysql/ib_logfile0]: Skipping because of failed dependencies
==> twlight: Notice: /Stage[main]/Twlight::Configsys/File[/var/lib/mysql/ib_logfile1]: Dependency Package[nodejs] has failures: true
==> twlight: Warning: /Stage[main]/Twlight::Configsys/File[/var/lib/mysql/ib_logfile1]: Skipping because of failed dependencies
==> twlight: Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/content: content changed '{md5}272b568cc9fc1ccc5d01b200df3cd73a' to '{md5}b79a158497b53fc210d8b71538762c32'
==> twlight: Error: /Stage[main]/Mysql::Server::Service/Service[mysqld]: Failed to call refresh: Systemd restart for mysql failed!
==> twlight: journalctl log for mysql:
==> twlight: -- Logs begin at Sun 2019-03-24 10:06:12 UTC, end at Sun 2019-03-24 10:35:55 UTC. --
==> twlight: Mar 24 10:31:21 twlight systemd[1]: Stopped LSB: Start and stop the mysql database server daemon.
==> twlight:
==> twlight: Error: /Stage[main]/Mysql::Server::Service/Service[mysqld]: Systemd restart for mysql failed!
==> twlight: journalctl log for mysql:
==> twlight: -- Logs begin at Sun 2019-03-24 10:06:12 UTC, end at Sun 2019-03-24 10:35:55 UTC. --
==> twlight: Mar 24 10:31:21 twlight systemd[1]: Stopped LSB: Start and stop the mysql database server daemon.
==> twlight:
==> twlight: Error: 'test -S /tmp/mysql.sock' returned 1 instead of one of [0]
==> twlight: Error: /Stage[main]/Mysql::Server::Service/Exec[wait_for_mysql_socket_to_open]/returns: change from notrun to 0 failed: 'test -S /tmp/mysql.sock' returned 1 instead of one of [0]
==> twlight: Error: /Stage[main]/Mysql::Server::Service/Exec[wait_for_mysql_socket_to_open]: Failed to call refresh: 'test -S /tmp/mysql.sock' returned 1 instead of one of [0]
==> twlight: Error: /Stage[main]/Mysql::Server::Service/Exec[wait_for_mysql_socket_to_open]: 'test -S /tmp/mysql.sock' returned 1 instead of one of [0]
==> twlight: Notice: /Stage[main]/Mysql::Server::Root_password/Exec[remove install pass]: Dependency Exec[wait_for_mysql_socket_to_open] has failures: true
==> twlight: Warning: /Stage[main]/Mysql::Server::Root_password/Exec[remove install pass]: Skipping because of failed dependencies
==> twlight: Error: Failed to apply catalog: Execution of '/usr/bin/mysql -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Please help!

**Comment by jsnshrmn** [comment]
Hmm, this indicates that mariadb isn't getting installed.

**Comment by gaurav7019** [comment]
@jsnshrmn The issue was resolved.
